services:
  - type: web
    name: erp-2ig-backend
    runtime: node
    region: frankfurt
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss && node src/seed.js
    startCommand: node src/index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BACKUP_DIR
        value: /tmp/erp-2ig-backups

  - type: web
    name: erp-2ig-frontend
    runtime: static
    region: frankfurt
    rootDir: frontend
    buildCommand: npm install && npm run build
    nodeVersion: 22.12.0
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        sync: false
